name = "hackthe6ix-landing-worker-dev"
main = "src/index.ts"
compatibility_date = "2023-05-21"

[vars]
# Development should use .dev.vars
MAILTRAIN_PUBLIC_ROOT_PATH = "https://mailtrain.hackthe6ix.com" # No trailing slash
MAILTRAIN_MAILING_LIST_ID = ""
MAILTRAIN_CONTACT_TEMPLATE_CID = ""
CONTACT_EMAIL = ""

# Secrets:
MAILTRAIN_API_KEY = ""
CAPTCHA_SECRET_KEY = ""

[env.production]
name = "hackthe6ix-landing-worker"
routes = [
    { pattern = "landingapi.hackthe6ix.com", custom_domain = true }
]
