name = "hackthe6ix-landing-worker-dev"
main = "src/index.ts"
compatibility_date = "2023-05-21"

[build]
command = "npm run build"

[vars]
# Development should use .dev.vars
MAILTRAIN_PUBLIC_ROOT_PATH = "http" # No trailing slash
MAILTRAIN_MAILING_LIST_ID = ""
MAILTRAIN_CONTACT_TEMPLATE_CID = ""
CONTACT_EMAIL = ""

# Secrets:
MAILTRAIN_API_KEY = ""


[env.production]
name = "hackthe6ix-landing-worker"
routes = [
    { pattern = "landingapi.hackthe6ix.com", custom_domain = true }
]
