name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Apply Wrangler Configuration
        run: |
          echo $WRANGLER_FILE_CONTENT | base64 -d > wrangler.toml
        shell: bash
        env:
          WRANGLER_FILE_CONTENT: ${{secrets.WRANGLER_FILE_CONTENT}}
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: "production"
          secrets: |
            MAILTRAIN_API_KEY
        env:
          MAILTRAIN_API_KEY: ${{ secrets.MAILTRAIN_API_KEY }}