name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - name: Apply Wrangler Configuration
        run: |
          echo $WRANGLER_FILE_CONTENT_B64 | base64 -d > wrangler.toml
        shell: bash
        env:
          WRANGLER_FILE_CONTENT_B64: ${{secrets.WRANGLER_FILE_CONTENT_B64}}
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: "production"
          secrets: |
            MAILTRAIN_API_KEY
        env:
          MAILTRAIN_API_KEY: ${{ secrets.MAILTRAIN_API_KEY }}